#controllers:
    #resource: ../../src/Controller/
    #type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

web_controller:
    resource: ../../src/Controller/
    type: annotation
rest_controller:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api