login:
    path: /
    controller: App\Controller\SecurityController::login
    
app_logout:
    path: /logout
  
app_homepage:
    path: /page/{num_page}
    controller: App\Controller\PageController::index
    requirements:
        num_page: '[1-2]'
    