<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0oq2Zx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0oq2Zx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX0oq2Zx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX0oq2Zx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX0oq2Zx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X0oq2Zx',
    'container.build_id' => '03bc9c17',
    'container.build_time' => 1625502811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0oq2Zx');
