<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2tiz7Rg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2tiz7Rg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2tiz7Rg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2tiz7Rg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2tiz7Rg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2tiz7Rg',
    'container.build_id' => '8bbee181',
    'container.build_time' => 1625497411,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2tiz7Rg');
